version: "3"

services:
  mapit:
    build: .
    volumes:
      - ./conf/general.yml-docker:/usr/src/app/conf/general.yml
      - static_files:/usr/src/collected_static

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf-docker:/etc/nginx/conf.d/default.conf
      - static_files:/static
    depends_on:
      - mapit

volumes:
  static_files:
  